### ISSUE TITLE
Making the package extensible? 

### ISSUE THREAD

**Issue by linhtto** [viktorstrate/vscode-latex-utilities#3]
I think it'd be really cool to have an easy way for the user to expand this package for other commands that will be applied to the selected text. I'm thinking of \emph right now to go with what's already there, but there are many others: change font size \footnotesize, text color \color, etc. To be safe, the curly braces should be both inside and outside of the command: `{\footnotesize{SELECTED TEXT}}`. The only thing the user should define is a list of commands, and a way to assign keybindings for any of them.

**Comment by linhtto** [comment]
Another way to explain what I have in mind: https://github.com/SublimeText/LaTeXTools/blob/master/docs/keybindings.md see section "Wrapping existing text in commands and environments".

**Comment by viktorstrate** [comment]
That's a very good idea, that would make the project more modular. I didn't know of _LaTeXTools_ for sublime, but it looks much like what I imagined this plugin being like.

**Comment by viktorstrate** [comment]
I cannot find a way for users to add custom commands dynimcally, so my solution was to add a command called `Wrap selection in custom command`, which will propt the user to enter the custom command, which then will be used as the keyword.

And i've added the emphasize wrap command as you mentioned.

**Comment by linhtto** [comment]
That's awesome. Thank you!

**Comment by linhtto** [comment]
One last small thing: As I mentioned, for certain "global" commands like \footnotesize, sometimes they need to be wrapped inside curly braces themselves {\footnotesize{text}} or else their effect continues on. Is there a way to add another shortcut to just create a surrounding pair of braces? So if I already have \footnotesize{text} highlighted, I hit this shortcut, and it gives me {\footnotesize{text}}.

Thanks!

**Comment by linhtto** [comment]
This is a side note, but I notice that right now the onLanguage activation just has "latex", which is probably enough for most people including me, but just in case, maybe you want all of these?
```    
    "onLanguage:tex",
    "onLanguage:latex",
    "onLanguage:doctex",
```

**Comment by viktorstrate** [comment]
To solve the problem with tags like footnotesize, extending beyond what's intended. I think the best solution would be, to make a predefined list of theese kinds of commands, and only add extra surrounding braces to theese commands.

As for the _onLanguage activation_, I think that is a good idea.

**Comment by linhtto** [comment]
I see. I just thought the ability to surround text with curly braces can be
helpful generally as well. So then one wouldn't need to decide when that's
necessary. It does require two steps to achieve with the two layers but
it's probably not often and it's more flexible that way.

**Comment by viktorstrate** [comment]
As of right now, this is only related to 'custom' commands. Therefore a solution could also be to make another command like `wrapCustomCommand` called `wrapCustomCommandOuterBraces` or somthing like that, which surrounds the selection with braces.

**Comment by linhtto** [comment]
That would work fine with me if that's possible. I'd definitely use that
function. Thank you.

**Comment by viktorstrate** [comment]
Added in commit 40619f0

**Comment by linhtto** [comment]
Hi, I'm just wondering if this is pushed through yet, the package seems unchanged to me.

**Comment by viktorstrate** [comment]
I have just pushed it, it should show up in the marketsplace as 1.4.2 soon.
