### ISSUE TITLE
Merge-ish Request

### ISSUE THREAD

**Issue by tecosaur** [viktorstrate/vscode-latex-utilities#5]
Hi @viktorstrate,

This extension seems to implement exactly something that I'm currently trying to add to LaTeX-workshop [James-Yu/LaTeX-Workshop#809](https://github.com/James-Yu/LaTeX-Workshop/issues/809), and have run into a roadblock with. Would you be interested in helping make this functionality be added to LaTeX-workshop? or allow me to steal your code (with due credit)?

Thanks,
tecosaur

**Comment by viktorstrate** [comment]
I would be happy to help, I think the best solution would be, if LaTeX-Workshop adobted all the features of this project, so that users would only have to install one extension.

What are you currently trying to add to LaTeX-Workshop?

**Comment by tecosaur** [comment]
## My Plan™ V1.1

### What I've been trying to do / done (short version)

The short version is a bunch of keyboard shortcuts. I tried to do that by composing functioning shortcuts in my local copy of `keybindings.json` and then copied it over to `package.json` is vs code.

### Issue

Unfortunately, due to [Microsoft/vscode#31372](https://github.com/Microsoft/vscode/issues/31372) you can't provide snippet inserts from `package.json` so I've sort of hit a roadblock. Additionally, the ability in the extension to _toggle_ tags looks fantastic :)

### More Detail

These are the tags that I'm trying to _snippetize_: `emph` + *`text`* `bf`/`it`/`tt`/`sl`/`sc` + `underline` + `textsuperscript` + `textsubscript` + `textnormal` + *`math`* `bf`/`bb`/`it`/`rm`/`sf`/`cal`.

Yes I know that's a lot. The main one would be `textbf`, `emph`, and `mathrm` followed by `textsc`, `text` `super`/`sub` `script`, and `mathcal` (in my opinion).

### Desired Outcomes

I'm hoping that one of the following can be achieved
 - **[Ideal]** Your code is very compatible, and so all that's required is a pull request to LaTeX-workshop which has minor modifications, and can easily be modified to add all of the aforementioned tags.
 - **[Good]** You help give an understanding of what the core components for this functionality are, and they're ported over and modified to achieve the desired effect

### P.S.

I notice that no-snippets-keybindings-in-package issue I referenced looks like it may be solved in the near future, but your approach looks definitively better — so I'd still love to incorporate the work that you've done.

### P.P.S.
Regarding your auto-`\item`, I know that LaTeX-workshop tried implementing that and hit some sort of issue, it may be worth talking to the owner/main collaborator (James Yu and jlelong respectively)

### P.P.P.S.
I also have more plans for the future, based on what I find, and imagine other would also, the most useful. At the moment this includes:
 - Shortcuts for starting and *ending* environments (I recon ending would be particularly useful)
 - Shortcuts for inserting `sections`, `subsections`, … `subparagraphs`
 - Some way to change the _importance level_ (idk) of a section/subsection etc.
    - i.e. section ↔ subsection ↔ … ↔ paragraph ↔ subparagraph
 - An equivalent of [this](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) (auto enviroment renaming)

### P.P.P.P.S.
Sorry about the length.
